### PR TITLE
[WIP] Jupyter widget

### PR DESCRIPTION
**Pull request by anibalsolon**
Hi!

I've been working on this project so that I could use the fast rendering of Brainsprite into Jupyter notebooks.

There still several tasks to do, from loading volumes and converting to sprites, to better packaging to use the lib just by loading one file.

I want to know if you have any roadmap for the project and if my contributions are consistent for the roadmap.

### CODE REVIEW

**Comment by pbellec** [comment]
Dear Anibal,

Thanks a lot for your contribution. 

  There is no definitive roadmap for brainsprite at the moment. Some discussions have been happening on the #brainsprite channel of the [brainhack slack](https://brainhack-slack-invite.herokuapp.com/). You may also want to join the #ni-js channel, which should host discussions on a collective of javascript libraries for neuroimaging, similar to nipy for python.

    Having said that, integration of brainsprite in jupyter notebooks is absolutely on the roadmap (I just added a formal milestone for that), as well as generation of sprites using python. Note that it may be possible to do the generation of sprites entirely in javascript and make the library easily portable to R or Octave kernels as well, for example - I will explore that possibility as well. 

      I went through your PR and there are a lot of changes in there. Some are obviously valuable - I liked how you dealt with the default values, much cleaner. But others are unclear to me - for example I don't know why you moved the brainsprite.js library to a new folder, which will break all of the examples I think, and should break the tests as well.

It would be very useful if you could break down the PR into smaller chunks, with a single purpose. This would make it much easier for me to review and merge.

Best,

Pierre

**Comment by anibalsolon** [comment]
Awesome, @pbellec ! I did not know about the channel.

Yes, you are absolutely right, my PR got a little entangled. I tried to follow the template from Jupyter for new widgets ( https://github.com/jupyter-widgets/widget-cookiecutter ), but since Brainsprite is also a JS lib, its folder should remain as it is. I will break it into PRs as soon as possible.

A sprite generator based entirely on JS would be awesome! If you break down one of the axes, it becomes possible to parallelize the process into web-workers.

I will create new PRs as soon as possible :)

**Comment by pbellec** [comment]
I wish I had worked on this PR earlier. I have integrated the default values, at least that's a start. There are lots of changes re the jupyter widget API. The approach of nilearn has simply been to add an iframe to the notebook. That's what I am working on at the moment. The python project now lives here: https://github.com/brainsprite/brainsprite.py

**Comment by anibalsolon** [comment]
That is nice! Do you think it is possible to keep the widget state by using iframes? For example, when the user opens a notebook with results from a previous execution.

**Comment by pbellec** [comment]
No, the iframe approach is very limited. 

For example, if multiple viewers are present in the same notebook with the same background structural scan, the data of the structural scan needs to be updated.
  There is also no way to have the viewer interact with, say, a plot.
    brainsprite was designed to facilitate these types of interactions, so iframes are far from ideal.

If you are interested in building a full-featured brainsprite widget, I'd be interested in working with you on that one. Let me know.

**Comment by anibalsolon** [comment]
Sure, I'd be glad to help! Let me know how you want to coordinate this, we can chat on slack/skype.

**Pull request closed without merging**
